version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  frontend: # name of the first service
    # build: frontend # specify the directory of the Dockerfile
    image: rubru94/mean-stack-app-frontend:dev # specify image to build container from
    ports:
      - "4200:4200" # specify port forewarding

  backend: # name of the second service
    #build: backend # specify the directory of the Dockerfile
    image: rubru94/mean-stack-app-backend:dev # specify image to build container from
    links:
      - mongo-db
    ports:
      - "3000:3000" #specify ports forewarding

  mongo-db: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding